name: Run MATLAB Tests and Generate MEX files on GitHub-Hosted Runner
on:
  pull_request:
    types: [opened, reopened, review_requested]
  workflow_dispatch:
jobs:
  test:
    name: Legacy & OS Compatability Syntax Tests
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: R2021a
            products: Signal_Processing_Toolbox Parallel_Computing_Toolbox
      - name: Run Tests on Legacy version
        uses: matlab-actions/run-command@v2
        with:
          command: |
            parfor i = 1:3
              disp(i);
            end
